apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
